# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
â”Œ \
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$haskell\
$helm\
$java\
$julia\
$kotlin\
$lua\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$pulumi\
$purescript\
$python\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$kubernetes\
$conda\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$env_var\
$crystal\
$custom\
$sudo\
$cmd_duration\
$line_break\
$time\
$status\
$container\
$shell\
â”” \
$character"""

[character] # The name of the module we are configuring is "character"
success_symbol = "[\\$](bold green)" # The "success_symbol" segment is being set to "âœ" with the color "bold green"
error_symbol = "[\\$](bold red)" # The "success_symbol" segment is being set to "âœ" with the color "bold green"
vimcmd_symbol = "[\\$](bold green)"

[hostname]
style = "#74c7ec bold"
ssh_symbol = "ğŸ´ "

[aws]
style = "#74c7ec bold"
symbol = "îŒ½  "

[buf]
style = "#74c7ec bold"
symbol = "ï’ "

[c]
style = "#74c7ec bold"
symbol = "î˜ "

[conda]
style = "#74c7ec bold"
symbol = "ï„Œ "

[dart]
style = "#74c7ec bold"
symbol = "î˜ "

[directory]
style = "#cba6f7 bold"
read_only = " ó°Œ¾"

[docker_context]
style = "#74c7ec bold"
symbol = "ïŒˆ "

[elixir]
style = "#74c7ec bold"
symbol = "î‰µ "

[elm]
style = "#74c7ec bold"
symbol = "î˜¬ "

[git_branch]
symbol = "ï˜ "

[golang]
style = "#74c7ec bold"
symbol = "î˜§ "

[haskell]
style = "#74c7ec bold"
symbol = "ó°²’ "

[hg_branch]
style = "#74c7ec bold"
symbol = "ï˜ "

[java]
style = "#74c7ec bold"
symbol = "ó°¬· "

[julia]
style = "#74c7ec bold"
symbol = "î˜¤ "

[lua]
style = "#74c7ec bold"
symbol = "î˜  "

[memory_usage]
style = "#74c7ec bold"
symbol = "ó°› "

[meson]
style = "#74c7ec bold"
symbol = "ó°”· "

[nim]
style = "#74c7ec bold"
symbol = "ó°†¥ "

[nix_shell]
style = "#74c7ec bold"
symbol = "ïŒ“ "

[nodejs]
style = "#74c7ec bold"
symbol = "îœ˜ "

[package]
style = "#fab387 bold"
symbol = 'ï’‡ '

[python]
style = "#74c7ec bold"
symbol = "îˆµ "

[rlang]
style = "#74c7ec bold"
symbol = "ó°Ÿ” "

[ruby]
style = "#74c7ec bold"
symbol = "î‘ "

[rust]
style = "#74c7ec bold"
symbol = "ó±˜— "

[scala]
style = "#74c7ec bold"
symbol = "îœ· "

[spack]
style = "#74c7ec bold"

[kubernetes]
style = "#74c7ec bold"
symbol = "ó±ƒ¾ "
format = '[ $symbol($cluster/$namespace) ]($style)'
disabled = false
